# Generated by Django 4.2.5 on 2024-04-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
