# Generated by Django 4.2.5 on 2024-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
